# Generated by Django 5.0.2 on 2024-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postulacion',
            fields=[
                ('nombre_post', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('correo_post', models.TextField(max_length=50)),
                ('numero_post', models.IntegerField()),
                ('ocupacion_post', models.TextField(max_length=200)),
            ],
        ),
    ]
