# Generated by Django 5.0.6 on 2024-06-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mi_app', '0002_delete_postulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_post', models.TextField(max_length=50)),
                ('correo_post', models.TextField(max_length=50)),
                ('numero_post', models.IntegerField()),
                ('ocupacion_post', models.TextField(max_length=200)),
            ],
        ),
    ]
