# Generated by Django 5.0.6 on 2024-07-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.TextField(max_length=50)),
            ],
        ),
    ]
